mysql -u root -p$MYSQL_ROOT_PASSWORD <<EOF

CREATE USER '$MYSQL_REPLICATION_USER'@'%' IDENTIFIED WITH 'caching_sha2_password' BY '$MYSQL_REPLICATION_PASSWORD';

GRANT REPLICATION SLAVE ON *.* TO '$MYSQL_REPLICATION_USER'@'%';

ALTER USER '$MYSQL_USER'@'%' IDENTIFIED WITH 'caching_sha2_password' BY '$MYSQL_PASSWORD';

FLUSH PRIVILEGES;

EOF
